### DISCUSSION TITLE
Breaking Changes for Mappings API

### DISCUSSION THREAD

**Discussion by akurdunkar** [akurdunkar/gspt#14] [Announcements]
The mappings API has changed and now supports mode-specific mappings as in `normal/visual`

```yaml
mappings:
   view:
      mode:
       function: key
```

For e.g see the README
and for the default configuration please see  https://github.com/aditya-K2/gspt/blob/master/extras/CONFIG.md
